Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end
    # Set hostname for the VM
    config.vm.hostname = "ubuntu-vm"
    config.vm.network "private_network", ip: "192.168.33.10"
end